kind: Deployment
apiVersion: apps/v1
metadata:
  name: digitall-ocean
spec:
  selector:
    matchLabels:
      app: digitall-ocean
  template:
    metadata:
      labels:
        app: digitall-ocean
    spec:
      imagePullSecrets:
        - name: parmovi-harbor
      containers:
        - name: digitall-ocean
          image: {{YOUR_CONTAINER_REGISTERY}}/digitall-ocean:latest
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: digitall-ocean
spec:
  selector:
    app: digitall-ocean
  type: NodePort
  ports:
    - name: http
      port: 4200
      targetPort: 4200
      protocol: TCP
